project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Lenguajes de programacion: R"
  navbar:
    background: dark
    logo: "materiales/images/R_logo.svg.png"
    right:
    #   - icon: cloud-fill
    #     href: https://posit.cloud/spaces/397258
    #     text: Posit Cloud
    #   - icon: file-certificate
    #     href: license-web.qmd
    #   - icon: github
    #     href: https://github.com/kamecon/IntroToR/tree/master/courseS3/versionWeb
    #     text: GitHub
       - icon: envelope
         href: mailto:kromesoo@uax.es

    left:
      - href: index.qmd
        text: Home
      # - href: setup.qmd
      #   text: Packages & Data
      - text: Secciones
        menu:
        - text: "Introducción"
          href: materiales/01_introIde.qmd
        - text: "R: Básicos"
          href: materiales/02_basics.qmd
        - text: "Vectores y matrices"
          href: materiales/03_vectors.qmd
        - text: "Data frames"
          href: materiales/05_dataFrames.qmd
        - text: "Programación"
          href: materiales/08_programming.qmd
        # - text: "DuckdB"
        #   href: materiales/07_duckDb.qmd
        #   #target: "_blank"
        # - text: "Regression analysis"
        #   href: materials/10_regression.qmd
      #   - text: "Thank you 👋"
      #     href: materials/8_closing.qmd
      #     target: "_blank"
      - text: Ejercicios
        menu:
        - text: "¿Cómo crear un documento Quarto en RStudio?"
          href: materiales/1_ejercicios_intro.qmd
        - text: "Ejercicios 1: Tipos y variables"
          href: materiales/2_ejercicios_variablesYtipos.qmd
      #   - text: "Data Engineering Exercises"
      #     href: materials/3_data_engineering-exercises.qmd
      #   - text: "Arrow In-Memory Workflow Exercises"
      #     href: materials/5_arrow_single_file-exercises.qmd
      #   - text: "Data Manipulation Part II Exercises"
      #     href: materials/4_data_manipulation_2-exercises.qmd


format:
  html:
    theme: journal
    #css: styles.css
    toc: true
    toc-depth: 4
    link-external-newwindow: true

# editor: visual
# engine: knitr
# execute:
#   freeze: auto